#pragma once

// GENERATED by scripts/sync-golden-vectors.mjs from backend/src/lib/__fixtures__/signing-vectors.v1.json — do not edit.
// Every secret below is a dummy literal containing "not-real", so this file is safe to commit. Regenerate
// with `node scripts/sync-golden-vectors.mjs`; check for drift with `--check`.

struct GoldenVector
{
  const char *name;
  const char *secret;
  const char *deviceId;
  const char *topic;
  const char *body;
  const char *signature;
  const char *payload;
};

static const GoldenVector GOLDEN_VECTORS[] = {
  {
    R"RAW(single-temperature-sample)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
    R"RAW(b1a776ca532c46a3bc2538ee73d5d18aea3c0dbd85a126fdc682bc648b3c4a80)RAW",
    R"RAW(v1.b1a776ca532c46a3bc2538ee73d5d18aea3c0dbd85a126fdc682bc648b3c4a80.{"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
  },
  {
    R"RAW(multi-sample-batch)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}},{"recordedAt":"2023-11-14T22:15:20Z","values":{"temperature":28}}]})RAW",
    R"RAW(841d9a694c87870c95d6feecb216ec474480f3eb01a9fbcd8e08c16fb49f20c0)RAW",
    R"RAW(v1.841d9a694c87870c95d6feecb216ec474480f3eb01a9fbcd8e08c16fb49f20c0.{"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}},{"recordedAt":"2023-11-14T22:15:20Z","values":{"temperature":28}}]})RAW",
  },
  {
    R"RAW(second-device)RAW",
    R"RAW(golden-secret-not-real-BBBBBBBBBBBBBBBBBBBB)RAW",
    R"RAW(00000000-0000-4000-8000-000000000002)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000002/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":26.25}}]})RAW",
    R"RAW(c5e87c281d4238fca4c6e76649e4f1a1b411fdca4dc1764c2491040b873ca3f7)RAW",
    R"RAW(v1.c5e87c281d4238fca4c6e76649e4f1a1b411fdca4dc1764c2491040b873ca3f7.{"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":26.25}}]})RAW",
  },
  {
    R"RAW(temperature-and-turbidity)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}}]})RAW",
    R"RAW(bbbfe38d002607f2f1a0bc018d00be28853f47034b5ac3ba4b5d6db04140624e)RAW",
    R"RAW(v1.bbbfe38d002607f2f1a0bc018d00be28853f47034b5ac3ba4b5d6db04140624e.{"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}}]})RAW",
  },
  {
    R"RAW(turbidity-only-sample)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"turbidity":250.5}}]})RAW",
    R"RAW(9fddb24047cb0d6898a8cb69ca670e216a876a202f38f0b8099ff46213f9db4c)RAW",
    R"RAW(v1.9fddb24047cb0d6898a8cb69ca670e216a876a202f38f0b8099ff46213f9db4c.{"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"turbidity":250.5}}]})RAW",
  },
  {
    R"RAW(turbidity-nan-omitted-in-batch)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}}]})RAW",
    R"RAW(3c1543b542c635322db27ef4e1f1393e94ac82fb87eae4ec5c48f8671cdb6dcb)RAW",
    R"RAW(v1.3c1543b542c635322db27ef4e1f1393e94ac82fb87eae4ec5c48f8671cdb6dcb.{"firmwareVersion":"0.5.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}}]})RAW",
  },
  {
    R"RAW(wifi-ssid-awkward)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.5.0","wifiSsid":"Bahay \"Kubo\" \\ Café","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
    R"RAW(912bb6554a075faa733188e2437fe5f7bbd8a7ff550fa75b77131dfeef17eb54)RAW",
    R"RAW(v1.912bb6554a075faa733188e2437fe5f7bbd8a7ff550fa75b77131dfeef17eb54.{"firmwareVersion":"0.5.0","wifiSsid":"Bahay \"Kubo\" \\ Café","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
  },
};

static const unsigned GOLDEN_VECTOR_COUNT = 7;
