#pragma once

// GENERATED by scripts/sync-golden-vectors.mjs from backend/src/lib/__fixtures__/signing-vectors.v1.json — do not edit.
// Every secret below is a dummy literal containing "not-real", so this file is safe to commit. Regenerate
// with `node scripts/sync-golden-vectors.mjs`; check for drift with `--check`.

struct GoldenVector
{
  const char *name;
  const char *secret;
  const char *deviceId;
  const char *topic;
  const char *body;
  const char *signature;
  const char *payload;
};

static const GoldenVector GOLDEN_VECTORS[] = {
  {
    R"RAW(single-temperature-sample)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
    R"RAW(77d5f7ca60b8d97368c9d59807d2a15521afa17689b4bb86f13b6d1ca3ebdefc)RAW",
    R"RAW(v1.77d5f7ca60b8d97368c9d59807d2a15521afa17689b4bb86f13b6d1ca3ebdefc.{"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
  },
  {
    R"RAW(multi-sample-batch)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}},{"recordedAt":"2023-11-14T22:15:20Z","values":{"temperature":28}}]})RAW",
    R"RAW(b9a9559dbd2172cdc27bd0ef409805f5d1b53160fe6d4bfdcbb1f6d0d86efdca)RAW",
    R"RAW(v1.b9a9559dbd2172cdc27bd0ef409805f5d1b53160fe6d4bfdcbb1f6d0d86efdca.{"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}},{"recordedAt":"2023-11-14T22:15:20Z","values":{"temperature":28}}]})RAW",
  },
  {
    R"RAW(second-device)RAW",
    R"RAW(golden-secret-not-real-BBBBBBBBBBBBBBBBBBBB)RAW",
    R"RAW(00000000-0000-4000-8000-000000000002)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000002/readings)RAW",
    R"RAW({"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":26.25}}]})RAW",
    R"RAW(24b0b8bf1cb738b1591c3786f5ca5376671d751fe4ea64a142300a507d16c213)RAW",
    R"RAW(v1.24b0b8bf1cb738b1591c3786f5ca5376671d751fe4ea64a142300a507d16c213.{"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":26.25}}]})RAW",
  },
  {
    R"RAW(temperature-and-turbidity)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}}]})RAW",
    R"RAW(5118457eb43555cf4bac98e21ea3ac1930e6c9705089bc0787f842627dcf5265)RAW",
    R"RAW(v1.5118457eb43555cf4bac98e21ea3ac1930e6c9705089bc0787f842627dcf5265.{"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}}]})RAW",
  },
  {
    R"RAW(turbidity-only-sample)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"turbidity":250.5}}]})RAW",
    R"RAW(40667e896010e3d740d90cbf1eabf31bd2114c38a39dfe77ecb35c06b9b2633c)RAW",
    R"RAW(v1.40667e896010e3d740d90cbf1eabf31bd2114c38a39dfe77ecb35c06b9b2633c.{"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"turbidity":250.5}}]})RAW",
  },
  {
    R"RAW(turbidity-nan-omitted-in-batch)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}}]})RAW",
    R"RAW(221ad1105cc49140b9587ef2d3394057881dfcaad3abca47d6ea7bb4a5e9c656)RAW",
    R"RAW(v1.221ad1105cc49140b9587ef2d3394057881dfcaad3abca47d6ea7bb4a5e9c656.{"firmwareVersion":"0.4.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5,"turbidity":12.3}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}}]})RAW",
  },
};

static const unsigned GOLDEN_VECTOR_COUNT = 6;
