#pragma once

// GENERATED by scripts/sync-golden-vectors.mjs from backend/src/lib/__fixtures__/signing-vectors.v1.json — do not edit.
// Every secret below is a dummy literal containing "not-real", so this file is safe to commit. Regenerate
// with `node scripts/sync-golden-vectors.mjs`; check for drift with `--check`.

struct GoldenVector
{
  const char *name;
  const char *secret;
  const char *deviceId;
  const char *topic;
  const char *body;
  const char *signature;
  const char *payload;
};

static const GoldenVector GOLDEN_VECTORS[] = {
  {
    R"RAW(single-temperature-sample)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.3.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
    R"RAW(cbc82daad41ad84ec1896d9ec8885b42cfdade4b738922b31082f08db0cc7bf5)RAW",
    R"RAW(v1.cbc82daad41ad84ec1896d9ec8885b42cfdade4b738922b31082f08db0cc7bf5.{"firmwareVersion":"0.3.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}}]})RAW",
  },
  {
    R"RAW(multi-sample-batch)RAW",
    R"RAW(golden-secret-not-real-AAAAAAAAAAAAAAAAAAAA)RAW",
    R"RAW(00000000-0000-4000-8000-000000000001)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000001/readings)RAW",
    R"RAW({"firmwareVersion":"0.3.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}},{"recordedAt":"2023-11-14T22:15:20Z","values":{"temperature":28}}]})RAW",
    R"RAW(79264b4004a36866ccb3aa68f93c0db87836e7330f59bf6a260603ceb475a6f5)RAW",
    R"RAW(v1.79264b4004a36866ccb3aa68f93c0db87836e7330f59bf6a260603ceb475a6f5.{"firmwareVersion":"0.3.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":27.5}},{"recordedAt":"2023-11-14T22:14:20Z","values":{"temperature":26.25}},{"recordedAt":"2023-11-14T22:15:20Z","values":{"temperature":28}}]})RAW",
  },
  {
    R"RAW(second-device)RAW",
    R"RAW(golden-secret-not-real-BBBBBBBBBBBBBBBBBBBB)RAW",
    R"RAW(00000000-0000-4000-8000-000000000002)RAW",
    R"RAW(truaquality/v1/devices/00000000-0000-4000-8000-000000000002/readings)RAW",
    R"RAW({"firmwareVersion":"0.3.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":26.25}}]})RAW",
    R"RAW(3c9ab165d3b0bff1cacacc277b86544e5b3e73ca0f8351745a5bba2e0937d1ce)RAW",
    R"RAW(v1.3c9ab165d3b0bff1cacacc277b86544e5b3e73ca0f8351745a5bba2e0937d1ce.{"firmwareVersion":"0.3.0","samples":[{"recordedAt":"2023-11-14T22:13:20Z","values":{"temperature":26.25}}]})RAW",
  },
};

static const unsigned GOLDEN_VECTOR_COUNT = 3;
